name: unit tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python Dependencies
        run: |
          pip install -e ".[dev]"
      - name: Run tests
        run: python -m pytest tests
